project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Zhenggang Wang"
  site-url: https://zhenggang-wang.github.io/
  favicon: images/apple-touch-icon-180x180.png
  #repo-url: https://github.com/lianyujun/lianyujun.github.io
  #repo-actions: [edit, issue]
  
  navbar: 
    background: "#2C3E50"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Experience"
        href: experience.qmd


format:
  html:
    theme: styles.scss
    toc: false            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细
    grid:
      body-width: 900px  # 主体内容宽度
